local_enable=YES
write_enable=YES
local_umask=022
local_root=/var/www/wordpress
chroot_local_user=YES
allow_writeable_chroot=YES

pasv_enable=YES
pasv_address=127.0.0.1
seccomp_sandbox=NO
pasv_min_port=21100
pasv_max_port=21110
