# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cwong <cwong@student.hive.fi>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/22 07:14:17 by cwong             #+#    #+#              #
#    Updated: 2025/11/04 11:55:44 by nraatika         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC		:= cc
CFLAGS	:= -Wall -Wextra -Werror -g

NAME	:= libft.a

SRCS	:= ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c \
		   ft_isascii.c ft_isdigit.c ft_isprint.c ft_itoa.c ft_memchr.c \
		   ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c ft_putchar_fd.c \
		   ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c ft_split.c ft_strchr.c \
		   ft_strdup.c ft_striteri.c ft_strjoin.c ft_strlcat.c ft_strlcpy.c \
		   ft_strlen.c ft_strmapi.c ft_strncmp.c ft_strnstr.c ft_strrchr.c \
		   ft_strtrim.c ft_substr.c ft_tolower.c ft_toupper.c ft_printf.c\
		   ft_printf_utils.c

SRCS	+= get_next_line/get_next_line.c get_next_line/get_next_line_utils.c


OBJS	:= $(SRCS:.c=.o)

BONUS_SRCS	:= ft_lstadd_back_bonus.c ft_lstadd_front_bonus.c ft_lstlast_bonus.c \
			   ft_lstnew_bonus.c ft_lstsize_bonus.c ft_lstdelone_bonus.c \
			   ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstmap_bonus.c

BONUS_OBJS	:= $(BONUS_SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
	
bonus: .bonus

.bonus: $(OBJS) $(BONUS_OBJS)
	@touch .bonus;
	@ar rcs $(NAME) $(OBJS) $(BONUS_OBJS)
	
clean:
	rm -f $(OBJS) $(BONUS_OBJS) .bonus

fclean: clean
	rm -f $(NAME)

re: fclean all
